### ISSUE TITLE
When someone send u a video as a story even when it’s off you can’t replay it and it opens it

### ISSUE THREAD

**Issue by ros0fg** [SoCuul/BHInsta#11] opened 2024-03-03 16:42 UTC
Only videos : When someone send u a video as a story even when it’s off you can’t replay it and it opens it

**Comment by SoCuul** [comment] 2024-03-03 19:24
This is a duplicate of a known issue #5, closing this one to make it easier to track the progress of this issue.

**Closed by SoCuul** 2024-03-03 19:24 UTC
